### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by sgs006** [sgs006/Udacity-Yearbook-Project#14]
We need to figure out style guides for the site so people know what colors and such to style. Can anyone contribute to the discussion on style her or should we ask on the forum? Or do you think it would be too hectic asking about every design decision like that?

**Comment by sgs006** [comment]
It looks like the one consistent style won out on the forums. So we need to come up with color scheme etc.

**Comment by BelaWith1L** [comment]
My thoughts on this would be Google's rainbow color theme... I think that would be quite nice. :smiley:

**Comment by KatFrog** [comment]
I added a CSS stylesheet to the repository and started using the classes defined in yearbook.html to style the page.

**Comment by sgs006** [comment]
Looks great thanks.
