### ISSUE TITLE
Add Contributor File

### ISSUE THREAD

**Issue by SoteroX** [sgs006/Udacity-Yearbook-Project#2]
Add a contributor file that list all the people who contribute

**Comment by sgs006** [comment]
Ok sounds good

**Comment by SoteroX** [comment]
We should leave this issue open for someone on udacity to come and do

**Comment by TechnoConserve** [comment]
@SoteroX Out of curiosity, what is the benefit of having a file listing contributors when contributions are already tracked by GitHub?
