### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by sgs006** [sgs006/Udacity-Yearbook-Project#23]
So I tried styling my section on the yearbook page but it dose not seem to be working when I test the code in the preview.  Any clues as to what is going on?

**Comment by lloan** [comment]
Are you testing locally?

**Comment by sgs006** [comment]
I'm using this site https://htmlpreview.github.io/

**Comment by lloan** [comment]
Better off testing locally, sometimes it can take an hour or two for that to update, from what I've read. Caching issues and what not. Have you tried clearing your cache?

Much easier to work locally though.

**Comment by SoteroX** [comment]
@sgs006 it has to do with your style.css path in yearbook.html, try using 
`<link rel="stylesheet" href="public/stylesheets/style.css">`

**Comment by sgs006** [comment]
I'm not sure who was right, but it is working now. I'll try to work locally when I can. I was editing at work haha.
