### ISSUE TITLE
Need Feeback From Contributors

### ISSUE THREAD

**Issue by sgs006** [sgs006/Udacity-Yearbook-Project#35]
Hello Everyone. Still no Slack channel. I’m not sure they are going to give us one. The Poll for the style has completed and more people wanted to have a consistent theme throughout the site. Especially the yearbook page.

So I know we haven’t decided on colors and positioning and all of that stuff, but can we go ahead and start funneling people to the yearbook.html and resources.html documents to add their names and links?

On the resource page things are set up like so:

 `<h2 class="subheading">Guides</h2>`
    `<ol>`
      `<li><a href=#Link></a></li>`
   ` </ol>`
Students can come in and add links to the <ol> and add new subheadings as long as they have the subheading class. This page should be very simple and straightforward to add to and style since it is just a series of lists and links.

For the yearbook page we have this:

 `<div class="yearbook-section">`
    `<h2 class="yearbook-names">Sam Stokes</h2>`
    `<ul>`
     ` <li><a href="https://codepen.io/Mithrawn/pen/xpjJYQ">Mockup to Article</a></li>`
     ` <li><a href="https://codepen.io/Mithrawn/pen/ypEwqX">Animal Trading Card</a></li>`
     ` <li><a href="www.google.com">Pixelart Maker</a></li>`
  `  </ul>`
  `  <p class="yearbook-quote">Dream the impossible dream -Somebody</p>`
  `</div>`

Everyone that comes in will make a div with the class yearbook-section. Then they will make an `<h2>` with the class yearbook-names and write in their name. Then an `<ul>` with three links to their projects. If not done with a project they can just put in a placeholder for now. Next they can make a `<p>` with the class yearbook-quote and do a quote that they like. The idea here would be to have a nice consistent page where everyone could put easily “sign” the yearbook and make a contribution that does not take a ton of time and get experience using GitHub. I considered having a line of code here for an image but I’m afraid it would make the page too large or unwieldy. What are your thoughts about a personal photo? Also, should any of this example code change? I’m hoping to write up a guide or something to lead people on how to contribute so I want to get this nailed down. Thanks.

**Comment by KatFrog** [comment]
Two thoughts:
* I don't think that we should include project #1 here, because the focus of the project was using only HTML to mock up the article.  No one will (hopefully) ever just use HTML in a webpage.  
* I think that people should list the animal name with the trading card.  For example, I did a card on guinea pigs, so my link is called "Guinea Pig Trading Card".

**Comment by TechnoConserve** [comment]
We should use the README.md file to invite people to add their names and resource links. We can also encourage consistency there and explain what our vision is for how things should look in the end.

But the value of this project is probably more the experience of collaboration, so I would focus more on trying to encourage participation. 

This also illustrates the power of pull requests. If someone submits a pull request to add their name and resources but blatantly disregards the existing style, we can just politely explain to them our guidelines, reject the pull request, and invite them to resubmit once they've made the appropriate corrections to their code.

**Comment by sgs006** [comment]
Yea, I think that is probably a good idea TechnoConserve. What do y'all think about the code I have above? Should we make changes to it or use that as the template for adding content. I know Alenori had an idea to use a "card" system, but I wasn't sure if everyone adding pictures would get too unwieldy, because people would have to host their pictures through imgur or something and then link to them which just adds more work for people and might lower participation. Here is the card code he was thinking about https://www.w3schools.com/howto/howto_css_cards.asp What do y'all think?

**Comment by jamesperrin** [comment]
I created a seperate Slack workspace for the Udacity Yearbook Project.
If anyone is interested, here is the link to join.


[Udacity Yearbook Project Slack workspace](https://join.slack.com/t/udacity-yearbook/shared_invite/enQtMzA2NTIyNzIyNzU3LTE5ZjAwMTZlYmU5MzcxMjY2YWVjMzkwYzZhMjQ2ZDRjMGJlMTQyMWE5ZGY3MzA4ZGEyNTYyOWI3MGIwZWIyMzU)
