### ISSUE TITLE
Need to create branches for contributors

### ISSUE THREAD

**Issue by KatFrog** [sgs006/Udacity-Yearbook-Project#36]
Hello,

I think that we need to create different branches for people to work on, that get merged back into the master branch after the changes have been reviewed.  This will hopefully help us avoid conflicts when 2 people try to edit the same file in the master branch.

What does everyone think?

Kathryn

**Comment by sgs006** [comment]
I think that is a good idea. I think that everyone can create their own branches right?

**Comment by alenori** [comment]
Sounds good, just trying to get a little more acquainted with GitHub at the moment. Will be checking in after every lesson I finish.

**Comment by TechnoConserve** [comment]
Sure that works.

Best practice is actually that you create a separate branch for each issue or feature you're working on. You may have several commits in that new branch while you work to ensure everything is working the way you intend. When things have been tested thoroughly, then you would merge back into master. So ideally no one is developing straight off of the master branch.

That said, I think this repository should be a place where new people feel safe to experiment and make mistakes so I don't think it's necessarily a good idea to try to enforce best practices for all these things. So yeah, your idea could be a great way to ease people into working with version control systems and how they work.

**Comment by KatFrog** [comment]
Yes, you can.  If you open up a git bash window, type in "git branch <name>" to create a new branch with your name.

**Comment by KatFrog** [comment]
Yes, getting acquainted with version control is important.  Plus we can ask everyone to use the pull request system as well, since this is how regular development teams work.

**Comment by KatFrog** [comment]
Here's a good resource for learning how to create and merge branches: []( https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)

**Comment by sgs006** [comment]
Yea, when we are ready to start getting a lot of people in here we need to write up some kinda simple instructions so people can add their names or whatever easily.

**Comment by RobGoelz** [comment]
I have a separate fork that I'm working on in my own system and from there I'm using PR into the master branch. 

I also do a pull from master before I do any new work on my fork.

is a fork sufficient replacement for the branch?
