### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by SoteroX** [sgs006/Udacity-Yearbook-Project#4]
Someone should create the navbar and if you can make it responsive, links can be added later

**Comment by TechnoConserve** [comment]
Do we want to try and do everything from scratch or use an easy framework like Bootstrap?

**Comment by SoteroX** [comment]
its up to @sgs006 on what frameworks are aloud, but starting from scratch though I think would be better for beginners since it will teach them a lot

**Comment by JS-goose** [comment]
I agree with starting from scratch, I did include the Bootstrap CDN in the index.html just as a boiler plate.  If we end up not using Bootstrap or any framework I'm good with that.  It's whatever @ssg006 and the group decide.

**Comment by sgs006** [comment]
I don't mind what we use. I guess not using bootstrap will help beginners more. I created a nav bar and some styling in the css page. Please feel free to add to it as it is very basic. Also, I'm not sure how to make extra pages. Do I just make a page called resources.html for the resources page etc?

**Comment by TechnoConserve** [comment]
@sgs006 Yes, that makes sense to me.

**Comment by SoteroX** [comment]
@sgs006 yea than you would use the <a href="resources.html">Resource</a> and whoever clicks it would be sent to the resources.html

this show help with the navbar
https://www.w3schools.com/howto/howto_js_topnav_responsive.asp

**Comment by sgs006** [comment]
Thanks. I think I was able to fix the navbar up.
