### ISSUE TITLE
doubtful that HTML anchor tags in README markdown will allow links to open in new browser tabs

### ISSUE THREAD

**Issue by tyler-vs** [sgs006/Udacity-Yearbook-Project#60]
Saw this on stackoverflow https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank , may be better to opt for regular markdown links instead

```
<a href = "https://codepen.io/" target="_blank">CodePen</a>
```

to simply

```
[CodePen](https://codepen.io/)
```

**Comment by sgs006** [comment]
We removed that from the readme.
