### ISSUE TITLE
Hello everyone!  I want to contribute. Any leads on which files need to be work on?

### ISSUE THREAD

**Issue by Cynth42** [sgs006/Udacity-Yearbook-Project#83]
I like to contribute on this project.  I have done the basics.  Like forking and cloning.  I'm going through the files on my computer.  What needs to done now?  Any leads?  I'll be glad to help out here. Thanks!

**Comment by jamesperrin** [comment]
Cynthia,

I would start by reviewing this [post](https://discussions.udacity.com/t/udacity-yearbook-student-project-start-here/570642/143?u=jamesperrin). You can ask any of the Team Leaders if they need assistance with any tasks.

Thanks,
JP

**Comment by Cynth42** [comment]
Thanks JP- I'm reading the post!
